# Generated by Django 5.1.6 on 2025-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('BD', 'Bangladeshi'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('FF', 'Fast Food'), ('OT', 'Other'), ('', '-------Select Option-------')], default='', max_length=2),
        ),
    ]
