# Generated by Django 5.1.6 on 2025-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
